#!/usr/bin/env ruby

require 'fileutils'

Dir.chdir(__dir__) do
  src_dir = "#{ENV['HOME']}/.zprezto/runcoms/"
  unless File.exist?(src_dir)
    STDERR.puts 'zprezto files not found...'
    exit 1
  end

  dst_dir = 'zsh'
  puts 'Create ./zsh' unless File.exist?(dst_dir)

  unless File.directory?(dst_dir)
    STDERR.puts "#{dst_dir} is not a directory."
    exit 1
  end

  %w(zshrc zprofile zlogin zlogout zshenv).each do |e|
    src = "#{src_dir}#{e}"
    dst = "#{dst_dir}/.#{e}"
    unless File.exist?(src)
      puts "WARNING: #{e} does not exist at #{src_dir}"
      next
    end
    if File.exist?(dst)
      puts "WARNING: #{dst} will be overwritten..."
      FileUtils.rm(dst)
    end
    FileUtils.cp(src, dst)
  end
end
